# Generated by Django 5.2 on 2026-06-16 11:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_class_rep', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(help_text='e.g. CST101', max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('target_levels', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), help_text='List of target levels, e.g. [100, 200].', size=None)),
                ('target_departments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), help_text='List of target departments.', size=None)),
            ],
            options={
                'ordering': ['course_code'],
            },
        ),
    ]
