# Generated by Django 5.2 on 2026-06-16 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='course',
            name='academic_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='users.lecturerprofile'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='classenrollment',
            unique_together={('student', 'course')},
        ),
    ]
